apiVersion: apps/v1
kind: Deployment
metadata:
  name: stunnel
  labels:
    app: stunnel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stunnel
  template:
    metadata:
      labels:
        app: stunnel
    spec:
      containers:
      - name: stunnel
        image: gcr.io/user-0001/stunnel:v1
        ports:
        - containerPort: 6378
        volumeMounts:
        - name: sec
          mountPath: /secret/server_ca.pem
          subPath: server_ca.pem
          readOnly: true
          #command: ["bash", "start_stunnel.sh"]
      volumes:
      - name: sec
        secret:
          secretName: casecret